client_config_backend: settings
client_config:
  client_id: 476844525174-4pr27607bo861j04vdbdejoq8f6o5m40.apps.googleusercontent.com
  client_secret: w4oaCqMlCeCzL0SiDHjMFWkq

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install